// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package CarreraProducer

import (
	"bytes"
	"fmt"
	"go.intra.xiaojukeji.com/golang/thrift-lib/0.9.2"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const PRESSURE_TRAFFIC_KEY = "isPressureTraffic"
const PRESSURE_TRAFFIC_ENABLE = "true"
const PRESSURE_TRAFFIC_DISABLE = "false"
const TRACE_ID = "traceId"
const SPAN_ID = "spanId"
const CARRERA_HEADERS = "carrera_headers"
const DIDI_HEADER_RID = "didi-header-rid"
const DIDI_HEADER_SPANID = "didi-header-spanid"

func init() {
}
