exports.SUBSCRIBE_ENABLE = 0;
exports.SUBSCRIBE_DISABLE = 1;

exports.TOPIC_DELAY_ENABLE = 0;
exports.TOPIC_DELAY_DISABLE = 1;

exports.GROUP_ALARM_ENABLE = 0;
exports.GROUP_ALARM_DISABLE = 1;

exports.SUBSCRIBE_CONSUMETYPE_SDK = 1;
exports.SUBSCRIBE_CONSUMETYPE_HTTP = 2;
exports.SUBSCRIBE_CONSUMETYPE_OTHER = 3;

exports.SUBSCRIBE_MSGTYPE_JSON = 1;
exports.SUBSCRIBE_MSGTYPE_TEXT = 2;
exports.SUBSCRIBE_MSGTYPE_BYTES = 3;

exports.SUBSCRIBE_GROOVY_ENABLE = 0;
exports.SUBSCRIBE_GROOVY_DISABLE = 1;

exports.SUBSCRIBE_TRANSIT_ENABLE = 0;
exports.SUBSCRIBE_TRANSIT_DISABLE = 1;

exports.SUBSCRIBE_ORDER_ENABLE = 0;
exports.SUBSCRIBE_ORDER_DISABLE = 1;

exports.SUBSCRIBE_ORDERKEY_QID = 'QID';
exports.SUBSCRIBE_ORDERKEY_KEY = 'KEY';
exports.SUBSCRIBE_ORDERKEY_JSONPATH = 'JsonPath';

exports.SUBSCRIBE_WRITETYPE_HDFS = 0;
exports.SUBSCRIBE_WRITETYPE_HBASE = 1;
exports.SUBSCRIBE_WRITETYPE_REDIS = 2;

exports.SUBSCRIBE_HTTPMETHOD_POST = 0;
exports.SUBSCRIBE_HTTPMETHOD_GET = 1;

exports.SUBSCRIBE_PRESSURE_ENABLE = 1;
exports.SUBSCRIBE_PRESSURE_DISABLE = 0;

exports.SUBSCRIBE_API_HIGHT_LEVEL = 1;
exports.SUBSCRIBE_API_LOW_LEVEL = 2;
