/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xiaojukeji.carrera.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class producerProxyConstants {

  public static final String PRESSURE_TRAFFIC_KEY = "isPressureTraffic";

  public static final String PRESSURE_TRAFFIC_ENABLE = "true";

  public static final String PRESSURE_TRAFFIC_DISABLE = "false";

  public static final String TRACE_ID = "traceId";

  public static final String SPAN_ID = "spanId";

  public static final String CARRERA_HEADERS = "carrera_headers";

}
